services:
  pgdatabase:
    image: postgres
    environment:
     - POSTGRES_USER=saputra
     - POSTGRES_PASSWORD=indonesia11
     - POSTGRES_DB=taxi 
    volumes:
     - "./../data:/var/lib/postgresql/data:rw"
    ports:
      - "5429:5432"
    container_name: pg-database
    networks:
      - data_engineer
      - v3_default

  pgadmins:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "9001:80"
    container_name: pg-admins
    networks:
      - data_engineer
      - v3_default

networks:
  data_engineer:
      external:
        name: data_engineer
  v3_default:
      external:
        name: v3_default
